valory-xyz/autonolas-frontend-mono

.github/workflows/govern.yml, .github/workflows/launch.yml, apps/govern/common-util/config/wagmi.ts, apps/govern/common-util/constants/addresses.ts, apps/govern/hooks/useFetchUserVotes.ts, apps/launch/common-util/config/wagmi.ts, apps/launch/common-util/constants/stakingContract.ts, apps/launch/components/Docs/index.tsx, apps/launch/components/MyStakingContracts/Create/index.tsx, apps/launch/components/Paths/PathDetail.tsx, libs/util-contracts/src/lib/abiAndAddresses/stakingFactory.js, libs/util-contracts/src/lib/abiAndAddresses/voteWeighting.js
_Awaits for activity checker addresses_
1) Added real contracts addresses
2) Added github workflow configs
3) Added remaining chains to configs
=> Prepare for Launch and Govern deploy

apps/launch/common-util/functions/stakingContract.ts
Fixes incorrect numbers converting, uses ethers instead
=> (launch) fix: incorrect numbers converting

apps/launch/common-util/functions/stakingContract.ts, apps/launch/components/MyStakingContracts/Create/index.spec.tsx, apps/launch/components/MyStakingContracts/Create/useFieldRules.tsx, apps/launch/components/MyStakingContracts/Details/ContractConfiguration.tsx
1) removes required rule from agentIds field
2) if not set, send as empty array
3) fix styles and url for agent ids on details page
=> (launch) fix: allow empty agentIds

README.md, apps/autonolas-registry/common-util/Details/DetailsSubInfo/RewardsSection.tsx, apps/launch/public/paths-markdown/launch-your-own-idea.md, apps/launch/public/paths-markdown/start-from-a-kit.md, libs/util-constants/src/lib/appUrls.ts
Removes links to tokenomics and member apps
=> chore: remove tokenomics and member links

apps/operate/components/Contracts/hooks.ts, apps/operate/components/Contracts/index.tsx
Checks available rewards value, if zero - show available slots as 0
=> (operate) fix: incorrect available slots calculation

apps/operate/components/Contracts/hooks.ts
- Update availability for new staking contracts 
=> (operate) feat: update "Available on" for new staking contracts

apps/launch/components/MyStakingContracts/Create/index.spec.tsx, apps/launch/components/MyStakingContracts/Create/index.tsx, apps/launch/components/MyStakingContracts/Create/useFieldRules.tsx
Fix hardcoded validation 
https://github.com/user-attachments/assets/6d028bbc-3de2-4912-9e94-902a0250e286
=> (launch) fix: replace hardcode with form value

apps/bond/components/PathContent.jsx
Changed text link for path no 7 to "Bond LP Tokens". 
=> chore: added bonding product link

apps/autonolas-registry/components/ListServices/ServiceState/utils.jsx
Added gas estimation to each service step. Tested each on a virtual test net, works fine, gas estimated fine, though for some reason it shows 'this transaction is likely to fail'—even though it doesn't (I see the same message without specifying gasLimit).
Anyway, with gas estimation we'll at least see the transaction revert error immediately in the console before signing the transaction
=> (registry) fix: add gas estimation to service steps

apps/operate/components/Contracts/hooks.ts
Adds latest contracts to the config
=> (operate) chore: update staking fields

apps/govern/components/Proposals/ProposalDetails.tsx, apps/govern/components/Proposals/ProposalsList.tsx
1) Add proposal Id
2) Display "Waiting to queue" status when proposal ended but not queued yet
=> (govern): fix status, add proposal id

apps/bond/components/BondingProducts/Bonding/BondingList/BondingList.jsx
1) fix guide links
2) remove external link, as paths are in the same app now
=> (bond): fix guide links

apps/govern/components/Proposals/index.tsx
Change snapshot link to the new UI 
=> (govern) chore: fix snapshot link

apps/bond/components/BondingProducts/Bonding/BondingList/BondingList.jsx, apps/bond/components/BondingProducts/Bonding/BondingList/useBondingList.jsx, apps/bond/components/BondingProducts/Bonding/BondingList/utils.js
The bonding list view had inconsistent information across products. Adding a new column fixes it and makes it more informative.
https://github.com/user-attachments/assets/aaf70519-4ac7-460e-bf6d-e6e2d24dcef1
Other data fixes with lp token info
=> (bond) fix: data displayed in bonding table

apps/operate/components/Contracts/hooks.ts, apps/operate/components/Contracts/index.tsx, apps/operate/components/RunAgentButton.tsx, apps/operate/types/index.ts
adds links to contribute for contribute staking contracts
=> (operate) feat: update availableOn for contribute contracts

apps/autonolas-registry/common-util/Contracts/addresses.tsx
Update GnosisSafeMultisig addresses for Optimism and Base
=> (registry) chore: update multisig addresses

apps/govern/components/Donate/index.tsx
=> (govern) chore: uncomment epoch section

apps/operate/components/Contracts/hooks.ts
=> (operate) chore: update contracts data

apps/govern/components/Contract/index.tsx, apps/operate/components/Agents.tsx, apps/operate/components/Contracts/hooks.ts, apps/operate/components/Contracts/index.tsx, apps/operate/components/RunAgentButton.tsx, apps/operate/types/index.ts
1) update costs and availability of the contracts
2) add the ability to show multiple buttons in the availability column (e.g. for optimus)
=> feat: update contracts availability and costs

apps/govern/components/Proposals/ProposalDetails.tsx, apps/govern/components/Proposals/ProposalsList.tsx
1) allow open proposal by proposalId in the URL
2) add transaction link 
=> feat: open proposal by id in URL

apps/operate/components/Contracts/hooks.ts, apps/operate/components/Contracts/index.tsx
Update operate app with contribute contracts
=> feat: update contracts availability

apps/govern/hooks/useNomineesWeights.ts
https://govern-git-tanya-govern-fix-autonolas.vercel.app/contracts
=> feat: take staking inflation into account for weights

apps/autonolas-registry/components/Layout/index.jsx, apps/bond/components/Layout/index.jsx, apps/govern/components/Layout/index.tsx, apps/launch/components/Layout/index.tsx, apps/operate/components/Layout/index.tsx, libs/ui-components/src/index.ts, libs/ui-components/src/lib/NavDropdown.tsx, libs/ui-theme/src/lib/GlobalStyles.tsx, tsconfig.base.json
Added header dropdowns to operate, launch, govern, bond and registry.
=> feat: added header dropdowns for easier navigation between sites

apps/operate/components/RunAgentButton.tsx
DO NOT MERGE
update QS links in accordance with https://trello.com/c/U9KJWIU3/2361-existing-non-traders-qs-users-can-run-the-same-agents-using-the-new-qs
=> feat: update non-trader QS links

apps/autonolas-registry/next.config.js, apps/bond/components/Home/Hero.jsx, apps/bond/next.config.js, apps/govern/components/Meta.tsx, apps/govern/next.config.js, apps/govern/pages/_app.tsx, apps/govern/pages/veolas.tsx, apps/launch/components/Meta.tsx, apps/launch/next.config.js, apps/launch/pages/_app.tsx, apps/operate/components/Meta.tsx, apps/operate/next.config.js, apps/operate/pages/_app.tsx
SEO fixes for SEMrush on Govern, Bond, Launch, Operate and Registry:
* locales added
* h1 headings 
* title tags
* meta descriptions
=> chore: seo fixes for apps

libs/common-middleware/src/lib/cspHeader.ts
- Bonding product list to load without error
- Cause: RPC issue (also updated in Vercel)
=> [bond] fix: bonding-products list

apps/govern/common-util/config/wagmi.ts
Possibly fixes issues with safe interactions
=> fix: safe interactions

apps/govern/components/Donate/index.tsx
=> [Govern UI] Show "Start new epoch" button 

apps/govern/components/Proposals/ProposalsList.tsx, apps/govern/components/Proposals/utils.ts
Adds two new status' states in order to reflect the correct status of the proposal in case it is not accepted.
https://linear.app/valory-xyz/issue/BDMARK-25
=> (govern) fix: not accepted proposal status

apps/bond/common-util/config/wagmi.js, apps/build/components/Login/config.ts, apps/build/components/Paths/index.tsx, apps/launch/common-util/config/wagmi.ts, apps/launch/project.json, apps/operate/common-util/config/wagmi.ts, apps/operate/project.json, apps/tokenomics/common-util/config/wagmi.js, apps/tokenomics/project.json
1. Adds `ssr` flag to wagmi configs, details here: https://wagmi.sh/react/guides/ssr
2. Center align post images (build)
=> (bond) fix: add ssr flag to wallet config

apps/build/middleware.ts, apps/build/next.config.js, apps/mech/middleware.ts, apps/mech/next.config.js
Adds middleware to build & mech apps as per [this](https://docs.google.com/document/d/1SOj0_g8Ef_hNFUCC7fPnUAzY5oi8gOjy7qvKd6uIyCM/edit?tab=t.0) doc
=> fix: add middleware to apps

apps/build/common-util/hooks/useFetchPathData.ts, apps/build/pages/paths/[id].tsx
Fixes the path not found issue caused by server side call redirection by the middleware (lies in US)
=> (build) fix: path not found issue

apps/build/components/Opportunities/index.tsx
Replaced Ralph telegram contact with mailto sales@valory
](https://linear.app/valory-xyz/issue/BDMARK-645)
=> chore: replaced mailing contact

apps/operate/components/Contracts/hooks.ts, apps/operate/components/Contracts/index.tsx, apps/operate/types/index.ts
* Put chain underneath contract name in same row
* Added new row with epoch and time remaining + tooltip explanation
Numbers compared with agent-stats script:
=> Style: added epoch and time remaining to contracts table

apps/autonolas-registry/common-util/List/ListTable/helpers.tsx, apps/autonolas-registry/common-util/functions/ifps.tsx, apps/autonolas-registry/common-util/hooks/useHandleRoute.jsx, apps/autonolas-registry/common-util/hooks/useHelpers.tsx, apps/autonolas-registry/common-util/subgraphs/index.tsx, apps/autonolas-registry/components/ListServices/hooks/useServicesList.jsx, apps/autonolas-registry/components/ListServices/hooks/useSvmService.tsx, apps/autonolas-registry/components/ListServices/index.tsx, apps/autonolas-registry/components/ListServices/utils.tsx, apps/autonolas-registry/pages/api/services.ts, apps/autonolas-registry/util/constants.ts
=> feat: list services

apps/autonolas-registry/common-util/ContractUtils/myList.jsx, apps/autonolas-registry/common-util/List/ListCommon.jsx, apps/autonolas-registry/common-util/List/ListTable/ListTable.jsx, apps/autonolas-registry/common-util/List/ListTable/helpers.tsx, apps/autonolas-registry/common-util/List/ListTable/useExtraTabContent.tsx, apps/autonolas-registry/common-util/functions/ifps.tsx, apps/autonolas-registry/common-util/functions/index.ts, apps/autonolas-registry/common-util/subgraphs/index.tsx, apps/autonolas-registry/components/Layout/Footer.jsx, apps/autonolas-registry/components/Layout/index.jsx, apps/autonolas-registry/components/Layout/styles.jsx, apps/autonolas-registry/components/ListAgents/index.jsx, apps/autonolas-registry/components/ListAgents/mint.jsx, apps/autonolas-registry/components/ListComponents/index.jsx, apps/autonolas-registry/components/ListComponents/mint.jsx, apps/autonolas-registry/components/ListServices/hooks/useServicesList.jsx, apps/autonolas-registry/components/ListServices/hooks/useSvmService.tsx, apps/autonolas-registry/components/ListServices/index.tsx, apps/autonolas-registry/components/ListServices/mint.jsx, apps/autonolas-registry/components/ListServices/servicesOfferedModal.tsx, apps/autonolas-registry/components/ListServices/utils.tsx, apps/autonolas-registry/components/styles.jsx, apps/autonolas-registry/pages/api/service-activity.ts, apps/autonolas-registry/pages/api/services.ts, apps/autonolas-registry/util/constants.ts, libs/common-middleware/src/lib/cspHeader.ts, libs/ui-theme/src/lib/ui-theme.tsx
=> feat: list services updates

apps/autonolas-registry/common-util/Details/ActivityDetails.tsx, apps/autonolas-registry/common-util/Details/index.tsx, apps/autonolas-registry/common-util/Details/styles.tsx
=> style: details page design

apps/autonolas-registry/components/NotLegal.jsx, apps/tokenomics/components/NotLegal.jsx, libs/util-prohibited-data/src/lib/prohibited-countries.json
remove usa from prohibited countries
=> chore: remove usa from prohibited countries

apps/marketplace/common-util/Details/index.tsx, apps/marketplace/common-util/graphql/service-activity.ts, apps/marketplace/common-util/types/index.ts, apps/marketplace/components/Layout/index.jsx
Gets the correct sender address for the delivery.
Also adds a redirect.
=> (marketplace) hf: correct sender address

apps/marketplace/common-util/Details/index.tsx, apps/marketplace/common-util/List/ListTable/helpers.tsx, apps/marketplace/common-util/graphql/service-activity.ts
Some requests might have null senders — reason is unknown right now, might be thegraph missing events. Adding a check to prevent breaking the UI for the user.
=> (marketplace) fix: null sender

apps/marketplace/next.config.js
Adds redirect for users still trying to access the mech's old links.
=> (marketplace) fix: mech app redirects

apps/contribute/components/Leaderboard/Campaigns/index.tsx
=> feat: remove hashtag from campaigns

apps/contribute/components/Leaderboard/Campaigns/index.tsx
=> fix: add descriptions for campaigns
